name: Run Python Script and Create PR

on:
  push:
    branches:
      - main
    paths:
      - assets/queries/**  # 👈 Replace this

jobs:
  run-script-and-pr:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: auto/gen-${{ github.run_id }}  # or use date +%s if preferred


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Python script
        run: python documentation/local_gen.py assets/queries/ --resources-json "documentation/resources.json" 

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Auto-generate files"

      - name: Push changes to new branch
        run: |
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-generate files"
          title: "Auto-generated files"
          body: "This PR was created automatically by a GitHub Action."
          branch: ${{ env.BRANCH_NAME }}

