name: Run Python Script and Create PR

on:
  push:
    branches:
      - main
    paths:
      - assets/queries/**

jobs:
  run-script-and-pr:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: auto/gen-${{ github.run_id }} 


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: pwd
        run: |
          ls
          ls documentation

      - name: Run Python script
        run: python documentation/local_gen.py assets/queries/ --resources-json "documentation/resources.json"

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit changes
        run: |
          git add .
          git diff --cached --quiet || git commit -m "Auto-generate files"

      - name: Push changes to new branch
        run: |
          git checkout -b $BRANCH_NAME
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-generate files"
          title: "Auto-generated files"
          body: "This PR was created automatically by a GitHub Action."
          base: ${{ env.BRANCH_NAME }}
          branch: main
          auto-merge: false
          sign-commits: true

