name: Run Python Script and Create PR

on:
  push:
    branches:
      - main
    paths:
      - assets/queries/**

jobs:
  run-script-and-pr:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: auto/gen-${{ github.run_id }} 


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: pwd
        run: |
          ls
          ls documentation

      - name: Checkout to new branch
        run: git checkout -b ${{ env.BRANCH_NAME }}

      - name: Run Python script
        run: python documentation/local_gen.py assets/queries/ --resources-json "documentation/resources.json"

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
      
      - name: Push branch
        run: git push origin ${{ env.BRANCH_NAME }}
