name: kics-github-action

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  kics-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run KICS Scan
        uses: checkmarx/kics-github-action@c06a133a98c75c2f920014d688015a5fb18095a4 # v2.1.10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: "./Dockerfile"
          ignore_on_exit: results
          enable_comments: true
          output_path: ./results
          output_formats: json,html
          type: dockerfile
      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        with:
          name: results
          path: ./results
